name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test against Rails ${{ matrix.rails }} with Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        rails: [
          '6.0.0',
          '6.1.0',
          '7.0.1',
        ]
        ruby: [
          '2.7',
          '3.0',
          '3.1',
          '3.2'
        ]
        exclude:
          - rails: '6.0.0'
            ruby: '3.1'
          - rails: '6.1.0'
            ruby: '3.1'
          - rails: '6.0.0'
            ruby: '3.2'
          - rails: '6.1.0'
            ruby: '3.2'

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false

    - name: Install Dependencies
      env:
        RAILS_VERSION: ${{ matrix.rails }}
        BUNDLE_PATH: "vendor/bundle-${{ matrix.rails }}"
      run: |
        sudo apt-get update
        sudo apt-get -yqq install libsqlite3-dev chromium-browser
        bundle install --jobs 4 --retry 3

    - name: Test
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails }}
        BUNDLE_PATH: "vendor/bundle-${{ matrix.rails }}"
        DEFAULT_TEST_EXCLUDE: ""
        RAILS_ENV: "test"

